<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><meta name="generator" content="rustdoc"><meta name="description" content="`@throw` and `@try/@catch` exceptions."><title>objc2::exception - Rust</title><script>if(window.location.protocol!=="file:")document.head.insertAdjacentHTML("beforeend","SourceSerif4-Regular-6b053e98.ttf.woff2,FiraSans-Italic-81dc35de.woff2,FiraSans-Regular-0fe48ade.woff2,FiraSans-MediumItalic-ccf7e434.woff2,FiraSans-Medium-e1aa3f0a.woff2,SourceCodePro-Regular-8badfe75.ttf.woff2,SourceCodePro-Semibold-aa29a496.ttf.woff2".split(",").map(f=>`<link rel="preload" as="font" type="font/woff2"href="../../static.files/${f}">`).join(""))</script><link rel="stylesheet" href="../../static.files/normalize-9960930a.css"><link rel="stylesheet" href="../../static.files/rustdoc-ca0dd0c4.css"><meta name="rustdoc-vars" data-root-path="../../" data-static-root-path="../../static.files/" data-current-crate="objc2" data-themes="" data-resource-suffix="" data-rustdoc-version="1.92.0-nightly (b925a865e 2025-10-09)" data-channel="nightly" data-search-js="search-8d3311b9.js" data-stringdex-js="stringdex-828709d0.js" data-settings-js="settings-c38705f0.js" ><script src="../../static.files/storage-e2aeef58.js"></script><script defer src="../sidebar-items.js"></script><script defer src="../../static.files/main-ce535bd0.js"></script><noscript><link rel="stylesheet" href="../../static.files/noscript-263c88ec.css"></noscript><link rel="alternate icon" type="image/png" href="../../static.files/favicon-32x32-eab170b8.png"><link rel="icon" type="image/svg+xml" href="../../static.files/favicon-044be391.svg"></head><body class="rustdoc mod"><!--[if lte IE 11]><div class="warning">This old browser is unsupported and will most likely display funky things.</div><![endif]--><rustdoc-topbar><h2><a href="#">Module exception</a></h2></rustdoc-topbar><nav class="sidebar"><div class="sidebar-crate"><h2><a href="../../objc2/index.html">objc2</a><span class="version">0.6.3</span></h2></div><div class="sidebar-elems"><section id="rustdoc-toc"><h2 class="location"><a href="#">Module exception</a></h2><h3><a href="#">Sections</a></h3><ul class="block top-toc"><li><a href="#throw-and-trycatch-exceptions" title="`@throw` and `@try/@catch` exceptions."><code>@throw</code> and <code>@try/@catch</code> exceptions.</a></li></ul><h3><a href="#structs">Module Items</a></h3><ul class="block"><li><a href="#structs" title="Structs">Structs</a></li></ul></section><div id="rustdoc-modnav"><h2 class="in-crate"><a href="../index.html">In crate objc2</a></h2></div></div></nav><div class="sidebar-resizer" title="Drag to resize sidebar"></div><main><div class="width-limiter"><section id="main-content" class="content"><div class="main-heading"><div class="rustdoc-breadcrumbs"><a href="../index.html">objc2</a></div><h1>Module <span>exception</span>&nbsp;<button id="copy-path" title="Copy item path to clipboard">Copy item path</button></h1><rustdoc-toolbar></rustdoc-toolbar><span class="sub-heading"><a class="src" href="../../src/objc2/exception.rs.html#1-434">Source</a> </span></div><details class="toggle top-doc" open><summary class="hideme"><span>Expand description</span></summary><div class="docblock"><h2 id="throw-and-trycatch-exceptions"><a class="doc-anchor" href="#throw-and-trycatch-exceptions">§</a><code>@throw</code> and <code>@try/@catch</code> exceptions.</h2>
<p>By default, if a message send (such as those generated with the
<a href="../macro.msg_send.html" title="macro objc2::msg_send"><code>msg_send!</code></a> and <a href="../macro.extern_methods.html" title="macro objc2::extern_methods"><code>extern_methods!</code></a> macros) causes an exception to be
thrown, <code>objc2</code> will simply let it unwind into Rust.</p>
<p>While not UB, it will likely end up aborting the process, since Rust
cannot catch foreign exceptions like Objective-C’s. However, <code>objc2</code> has
the <code>"catch-all"</code> Cargo feature, which, when enabled, wraps each message
send in a <code>@catch</code> and instead panics if an exception is caught, which
might lead to slightly better error messages.</p>
<p>Most of the functionality in this module is only available when the
<code>"exception"</code> feature is enabled.</p>
<p>See the following links for more information:</p>
<ul>
<li><a href="https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/Exceptions/Exceptions.html">Exception Programming Topics for Cocoa</a></li>
<li><a href="https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/ObjectiveC/Chapters/ocExceptionHandling.html">The Objective-C Programming Language - Exception Handling</a></li>
<li><a href="https://llvm.org/docs/ExceptionHandling.html">Exception Handling in LLVM</a></li>
</ul>
</div></details><h2 id="structs" class="section-header">Structs<a href="#structs" class="anchor">§</a></h2><dl class="item-table"><dt><a class="struct" href="struct.Exception.html" title="struct objc2::exception::Exception">Exception</a></dt><dd>An Objective-C exception.</dd></dl></section></div></main></body></html>